### ISSUE TITLE
Create Wiki Topics

### ISSUE THREAD

**Issue by AlyKitty** [barrycumbie/jobie-19#28]
Take some of the main topics from the comment/gist section and put them in their own wiki topics. These do collapse and so it makes it easier to see all of the topics.

**Comment by mcantrelldev** [comment]
Maybe designing a template for these topics would be a good suggestion to enhance readability and style. Otherwise you may get topics structured too differently.

**Comment by barrycumbie** [comment]
see @barrycumbie comments on #35 #39

**Comment by barrycumbie** [comment]
@AlyKitty can collaborators create and edit Wiki's? Do you have permission?What does it look like to public?

**Comment by AlyKitty** [comment]
@barrycumbie Yes, collaborators can edit/create Wiki's as long as they are able to write to the repositary. I do have permissions to create a new wiki page. Wikis are available to the public in public repositories.

**Comment by mattp281** [comment]
@AlyKitty submitted an edit to ensure that changes to could be made to wiki page

**Comment by mattp281** [comment]
@mcantrelldev @AlyKitty do we have a way to collaborate for this when everyone is not on Zoom? is there a chat we could have a running dialogue on?

**Comment by AlyKitty** [comment]
## Brainstorming: 
1. Create topics for the gist page and the wiki
  1.1 Wiki topics should be a little more broad and less technical so that the "public" can read it and still understand it.
  1.2 Gist topics should be more specific and day-to-day
2. Come up with a page layout for the wiki pages
  2.1 All wiki pages should have the same format/setup

**Comment by AlyKitty** [comment]
@mattp281 We could keep the commenting on here, though the same issue pops up where it will end up a little messy. I'm sure we could also create our own chat for the people working on this issue with whatever we choose.

**Comment by mattp281** [comment]
@AlyKitty will the Wiki page serve as a "summary" of the topics discussed on the gist page? How do we determine what the "main topics" are?

**Comment by AlyKitty** [comment]
@mattp281 I brought up in class a little early about leaving the wiki to a more public sort of documentation, if that makes sense. The gist page could be mainly for us, the students. Not sure if that is a good idea that people want to do or what.

**Comment by jeffreymccormick8** [comment]
@AlyKitty  From what I'm understanding, you're desire is to create this Wiki specifically for the product for people on the outside to see, correct?

What we were thinking in Issue #29 was to utilize the Wiki as the team/class container for class information in place of the class Gist.  The reason is, if we want to make changes to the Gist (i.e. formatting changes etc.) that process basically looks like this:

I have a change -> I comment change on Class Gist -> Cumbie sees comment -> Cumbie make change

Where maybe it should look something like this:

I have a change -> I make the change -> Cumbie approves the change

or just:

I have a change -> I make the change

**Comment by AlyKitty** [comment]
@jeffreymccormick8 I have no problem with using the wiki as a way to keep track of class info. I just brought up the idea and was waiting for feedback essentially. I personally just figured if we could clean up the gist and use that for our class notes and such then we could use the wiki as more of a professional way of documentation. So that way if we are able to put this on our resume they don't see all of our notes/comments/etc, they just see our process, whatever other information we provide, and the final product. 
I truly don't mind which way we pursue.

**Comment by jeffreymccormick8** [comment]
Ah. I gotcha. Proceed with your original thought. I was just curious. Thanks @AlyKitty!

**Comment by AlyKitty** [comment]
@jeffreymccormick8 If you guys want to use the wiki as a replacement for the gist page, then we will go that route and start figuring out how the format needs to look for that. I just need clarification as to which way we are going to do it. I don't think there is any wrong/right way to proceed with this.

**Comment by mattp281** [comment]
@AlyKitty I believe making the Wiki page as a replacement for the gist could run into some issues of that the gist is having. It would need to be cleaned up and filtered through after every class.  I think your idea of basically using the wiki to show main or crucial  topics in the comments or gist would be easier to manage.

**Comment by mcantrelldev** [comment]
As part of discussion in issue#29, we would like to make the class gist page into a simple "home" page on the wiki to eliminate any issues with only one person being the owner or looping back to Cumbie's original. We have a couple of wiki topic suggestions that I'm open to discussion on adding to the wiki.

**Comment by mcantrelldev** [comment]
Possible Topics for Wiki Export (Issue #28) off of the Gist:

- What is a Sprint/Scrum
- Tools
- Tech terminology
- Common Issues
- Standardized Pull Request
- Zoomland
-Question/Comments/Helpful Tips - Wiki page serving the purpose of the current gist comment section. Relevant comments get pushed to other wiki pages, such as a tip being reported here, later becomes a bullet point on common issues.

**Comment by AlyKitty** [comment]
I think those are good topics @mcantrelldev

**Comment by mattp281** [comment]
@mcantrelldev @AlyKitty so are we saying that the Wiki will be topic based not date? Issue #29 will be date oriented?

**Comment by Slavk1ng** [comment]
I think when we format the wiki it should go by topic and not by days.

**Comment by AlyKitty** [comment]
@mattp281 Switch into this breakout room so we all have the same conversation

**Comment by AlyKitty** [comment]
@mattp281 @Slavk1ng We aren't going off days though, no

**Comment by Slavk1ng** [comment]
Okay thanks!

**Comment by mcantrelldev** [comment]
A lot of cross-issue work is happening in Issue #29 related to the Wiki we may want to combine?

**Comment by AlyKitty** [comment]
@mcantrelldev I agree

**Comment by AlyKitty** [comment]
Closing this issue since it is a duplicate of issue #29
