### ISSUE TITLE
add tables to class notes

### ISSUE THREAD

**Issue by lovejoyy** [barrycumbie/jobie-19#39]
Create and implement tables to be more organized. Everyday you can create a new page numbered by day and week, this way we are able to refer to whatever day we need without having to see unwanted information. Over time these pages will turn into a portfolio for the entire semester.

**Comment by barrycumbie** [comment]
@lovejoyy is this for the online portfolio of team members or for our class notes? Do we want to organize by DAY or TOPIC (or both)? Maybe each day has the Zoom link, list of topics for that day and links to other Wiki articles? 

*Over time should be two words in this use. 

Can you edit this issue title to include an action word, write all in lowercase (unless something must be capitalized)? "add tables for class notes gist" 

@lovejoyy don't forget to assign yourself to this!

**Comment by lovejoyy** [comment]
closed and combined with issue #29
