### ISSUE TITLE
Pair up in teams

### ISSUE THREAD

**Issue by DelilahHowell** [barrycumbie/jobie-19#40]
Pick team members

**Comment by barrycumbie** [comment]
I agree BUT let's do this by issue. Once you can assign to an issue then you just hop on to any issue and that is who you are working with. 

- What if all 24+ join the same issue? 
- What if an issue is empty? 
- What if I have to do it all by my lonesome? 
- What if...something else? 

I dunno. Let's figure out when that happens. Until then, closing this one in favor of using the "Assignees" method per issue to work with a team.
